# Generated by Django 3.2.2 on 2021-05-09 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0002_auto_20210509_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subsription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('milk_choices', models.CharField(choices=[('1', '500ml'), ('2', '1000ml')], default='1', max_length=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='consumer.consumer')),
            ],
        ),
    ]
