# Generated by Django 3.2.2 on 2021-05-09 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0003_subsription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='door_no',
            field=models.CharField(max_length=10),
        ),
    ]
