# Generated by Django 3.2.2 on 2021-05-10 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0004_alter_address_door_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='user_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='consumer.address'),
        ),
    ]
